-d /home/jam/Downloads/kikad/solution/code_project/gowin/fpga_project/impl/gwsynthesis/fpga_project.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst /home/jam/Downloads/kikad/solution/code_project/gowin/fpga_project/src/fpga_project.cst
-cfg /home/jam/Downloads/kikad/solution/code_project/gowin/fpga_project/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
